### ISSUE TITLE
Non-Admin user sees logs from unassigned spaces (without app_name)

### ISSUE THREAD

**Issue by smuthuganesh** [cloudfoundry-community/firehose-to-syslog#110]
Hi,

We got firehose user (UAAC user) without admin scope.  Only the following scopes are given:
        uaac member add doppler.firehose [firehose user]
        uaac member add cloud_controller.read [firehose user]
        uaac member add cloud_controller.write [firehose user]

This firehose user has Space-Auditor Role for set of Spaces under a particular Org.  We expected to see logs ONLY from the apps under this Space under this Org.  But, we are getting logs from other Orgs too.

Also, If a log comes from the assigned Space (Org) apps' then it has cf_app_name, cf_org_id, cf_org_name, cf_space_id, cf_space_name details.  If a log comes from the unassigned Space (org) apps' then it is missing those details.  This part is just an observation and not the real issue which I am looking to resolve.  But, I don't want to see any of the logs from the unassigned Space (Org) apps.

Thanks.

**Comment by shinji62** [comment]
You are mis-undertanding right, firehose itself do not care about cloudfoundry user ...
You can listen to the firehose or you can not that the only things that the firehose care (doppler.firehose).

So that's why  you receive all logs from all org

Firehose-to-syslog use the same user to query the CF api to get the org, app, space name.
That's why you only get org space app name from the org you are authorize to.
