### ISSUE TITLE
Reduce load on Cloud Controller API

### ISSUE THREAD

**Issue by lisamcho** [cloudfoundry-community/firehose-to-syslog#181]
Frequently polling cloud_controller on the `v2/spaces/:guid/summary` endpoint can cause performance issues with the Cloud Controller API for Cloud Foundry deployments with a lot of apps/orgs/spaces. This is because this endpoint is similar to the `inline-relations-depth=2` query parameter in that it fetches levels of nested objects from the database, including all the routes for each app, as well as all the services in the space. It looks like [here](https://github.com/cloudfoundry-community/firehose-to-syslog/blob/ad2cb8e38091612624bc7e6eb1e06828a7d30cbf/events/events.go#L125-L164), the only fields that we are using for each app is space_guid, organization_guid, space_name, and organization_name.

It could be more efficient to fetch this metadata via the [apps list endpoint](https://apidocs.cloudfoundry.org/280/apps/list_all_apps.html), and then get the spaces and org names from the [organization list](https://apidocs.cloudfoundry.org/280/organizations/list_all_organizations.html) and [spaces list endpoint](https://apidocs.cloudfoundry.org/280/spaces/list_all_spaces.html).

**Comment by shinji62** [comment]
@lisamcho Thanks for you comments. First  suggestion from CAPI team was to remove this `IRD=2` call, now you say that the summary is still not good enough.  Calling apps endpoints then org then space could lead to 10K+ call top the CC (even more) what do you suggest.


Please feel free to contribute if you want.

**Comment by stwomack** [comment]
We are seeing very high performance hits to the CC Api, seemingly due to this scenario (tons of apps/orgs/spaces in this foundation). Are there any plans to relieve this issue?

**Comment by stwomack** [comment]
Oddly, setting `cc-pull-time = 0` had no effect. The CC slowness and failures continued.

**Comment by shinji62** [comment]
How many apps /spaces / orgs do you have ? How many instances of f2f do you have ? 
Can you count the number of f2f call to your CC ? (check the http agent)

**Comment by jgeorge300** [comment]
I'm experiencing this issue as well. I have 26 orgs. Each org has ~5 spaces. A couple have more than 10. I have 4 different f2s running with 2 instances each. We have to send different events to different end points. According to the toplogs-cloudcontroller.sh script, f2s had 1021945 requests in a 15 hour period while the next top requester (monit) only had 23264 requests.

**Comment by shinji62** [comment]
@jgeorge300 Did you try with the `cc-pull-time = 0` ?

**Comment by shinji62** [comment]
@aeijdenberg Thanks for the PR and the info. 
My customer have more than x 000 app and in some env, people are pushing a lot, so new app id and so on and of course across hundred and hundred of Orgs / Spaces

For the traffic (tps or qps) is more than 10K so having to lazy load a new app, could quickly help to fullfit the buffer.

Anyway I recognize the work and the improvement you did which is great ! What I would like, is too be a little more flexible, meaning choosing between a "lazy" and "old way" mode of loading from the CC.

I guess this is fair enough for people to try lazy and quickly go back to the old loading mode. 

Should not be difficult to add this options, and just add a new go file to implement the lazy mode. (You can even remove boltdDB if you want in the lazy implementation)


For your question
1 - Not everyone is running the nozzle as CF app.  People using it write to a disk which persist accross VM replacement and so on.
2 - Yes, if I recall but at the time we found that loading app in the background every X time should have been ok. 
3 - Not sure why you implement TTL ...

**Comment by aeijdenberg** [comment]
@shinji62 - I wonder if maybe the best of both worlds might be to initially do a big load before starting consumption of the firehose, and then combine lazy loading for new apps and a big slightly randomised TTL (to spread out requests) for refreshing app / space / org names?

In that manner the DB should be initially populated, and only new messages for new apps may trigger a momentary pause?

**Comment by shinji62** [comment]
@aeijdenberg If you pull CC time to `0` that's what happen mostly. We fully load the DB then on unknow apps we fill the DB.

Could just that calling space summary could be still expensive. I still think some call are expensive.

**Comment by aeijdenberg** [comment]
@shinji62 - thanks - I think I misread that code on first investigation. I suspect that setting that may well solve most of the issues we were looking to solve. I'll take a deeper look and maybe suggest a few small tidy up PRs.

Yes, enumerating apps seems extraordinarily slow from cloud controller, which seems like a problem worth solving on its own - though my Ruby knowledge isn't as extensive.

**Comment by shinji62** [comment]
@aeijdenberg any update on your side?

**Comment by aeijdenberg** [comment]
@shinji62 - not yet - other than we've been running our patched version without issue for about a week now and are seeing a big reduction in load across all our envs. I'll try to get back onto this shortly.

**Comment by aeijdenberg** [comment]
@shinji62 , I put an update on our progress in the PR: https://github.com/cloudfoundry-community/firehose-to-syslog/pull/192

I'll paste here too:

We've been running this for a few weeks now without issue and have seen a big drop in CPU usage on our API servers.

### Summary of changes:

1. Load all apps before starting to read from nozzle. In this manner we won't fill our buffer by falling behind before we have apps populated.
2. Instead of fetching all apps on scheduled basic, instead lazily re-fetch each app or space or org based on a randomized TTL.
3. Allow for in-memory cache instead of bolt if not persisting the database (which by default bosh release is not, as the default path is not in a persistent location).
4. Add options to strip app name suffixes. This is useful for blue/green and zero downtime pushes where apps typically have temporary suffixes during renames. Since this data is often incorrect anyway, we may as well strip it.
5. Stop using cf-client for important API calls, as it seems to often want to get smart and make successive calls for extra info that we don't need, contributing to latency and CPU load on API servers.

I think that's mostly it. We could also considering bumping the default TTL for the cached data from 60 seconds to something much larger, as the only effect of this being cached is if an app/space/org is renamed, which I imagine is a fairly rare event.

**Comment by shinji62** [comment]
@aeijdenberg Thanks, will take a look next week.

**Comment by Scoobed** [comment]
@shinji62 We would like to pull this version as it seems like a promising solution where our Cloud Controllers are seeing 7,000,000 404s a day because of the #4 in the list (blue-green deploys) and just caching in general.  Longer TTL is great idea too.  Do you have any idea when that will get out of the develop branch and be rolled into master?

**Comment by aeijdenberg** [comment]
It's probably waiting on me to update the tests. I'll submit a PR today to remove the failing tests - I realise there's probably more wanted, but it's at least better than tests that don't compile.

**Comment by shinji62** [comment]
@Scoobed as @aeijdenberg said I am waiting for it's PR for the test. So I guess new release will occur this week.

**Comment by aeijdenberg** [comment]
@shinji62 - have added some basic tests here: https://github.com/cloudfoundry-community/firehose-to-syslog/pull/196

**Comment by shinji62** [comment]
@Scoobed @aeijdenberg release 5.0.0 is now out. 
Please use it, and reopen this issue if needed.
