### ISSUE TITLE
Events that are from an app should have a real app name, space and org information.

### ISSUE THREAD

**Issue by simonjohansson** [cloudfoundry-community/firehose-to-syslog#8]
cf_app_id is a bit cryptic. 

```
cf curl "/v2/apps/942d2650-28e1-4214-a3ce-fc2bf21bda77?inline-relations-depth=2" | egrep "name|space|org"
      "name": "article-search-dev-0_2",
      "space_guid": "0e568373-a012-4991-9d64-d319fec988f4",
      "detected_start_command": "JAVA_HOME=$PWD/.java-buildpack/open_jdk_jre JAVA_OPTS=\"-Djava.io.tmpdir=$TMPDIR -XX:OnOutOfMemoryError=$PWD/.java-buildpack/open_jdk_jre/bin/killjava.sh -Xmx160M -Xms160M -XX:MaxMetaspaceSize=64M -XX:MetaspaceSize=64M -Xss853K -XX:+UseConcMarkSweepGC\" $PWD/article-search-0.2/bin/article-search",
      "space_url": "/v2/spaces/0e568373-a012-4991-9d64-d319fec988f4",
      "space": {
            "url": "/v2/spaces/0e568373-a012-4991-9d64-d319fec988f4",
            "name": "dev",
            "organization_guid": "19805aa5-2b47-4efd-a688-6a678e9773ce",
            "space_quota_definition_guid": null,
            "organization_url": "/v2/organizations/19805aa5-2b47-4efd-a688-6a678e9773ce",
            "organization": {
                  "url": "/v2/organizations/19805aa5-2b47-4efd-a688-6a678e9773ce",
                  "name": "casper",
                  "spaces_url": "/v2/organizations/19805aa5-2b47-4efd-a688-6a678e9773ce/spaces
```

https://github.com/logsearch/logsearch-for-cloudfoundry/pull/21

**Comment by simonjohansson** [comment]
https://github.com/cloudfoundry-community/go-cfclient could be used for this I think.

@rkoster mentioned this https://github.com/sourcegraph/apiproxy that could be used to provide caching.

**Comment by shinji62** [comment]
Yes caching is needed to avoid asking to CC every request.

**Comment by mrdavidlaing** [comment]
@simonjohansson Given that the loggregator team seem pretty adamant about no adding this information in loggregator - https://github.com/cloudfoundry/loggregator/issues/48 - and we would like this "firehose-to-syslog" nozzle to eventually be adopted by them; I propose that we don't add this functionality here.

I also think we can sidestep the whole caching complexity by leveraging the `translate` filter's ability to lookup values from an external text file.

I've put together a simple prototype of how this would work.  Essentially, 

* The [`cf_app_details_cache job`](https://github.com/logsearch/logsearch-for-cloudfoundry/blob/8e694e6f6004d684694e9ee57edcd4b69986809a/logsearch-for-cloudfoundry-boshrelease/jobs/cf_app_details_cache/templates/bin/cf_app_details_cache_ctl) creates a `yml` file containing the lookup information at `/var/vcap/store/cf_app_details_cache/cf_app_space_org_dictionary.yml`

        '9af4f832-32cf-47c1-bce8-f2e852ea0730': '{"cf_app_id":"9af4f832-32cf-47c1-bce8-f2e852ea0730","cf_app_name":"app-logs","cf_space_id":"5c98b860-f5d2-444c-b923-d91b277b5269","cf_space_name":"production","cf_org_id":"8005f45b-76d9-4038-8ca1-9e0a85ed5be0","cf_org_name":"system"}'
        '54967f0c-5069-4428-83de-84f86c1286e2': '{"cf_app_id":"54967f0c-5069-4428-83de-84f86c1286e2","cf_app_name":"devApp1","cf_space_id":"a871a722-cad2-4d46-8061-2c9b728b7d8f","cf_space_name":"development","cf_org_id":"8005f45b-76d9-4038-8ca1-9e0a85ed5be0","cf_org_name":"system"}'
* The log_filter rules use this lookup file as their [`dictionary_path`](https://github.com/logsearch/logsearch-for-cloudfoundry/commit/8e694e6f6004d684694e9ee57edcd4b69986809a#diff-6f5b81bbe16b56f441b1d056665895f3R65) to decorate each log message (reloading the file every [refresh_interval](http://www.elastic.co/guide/en/logstash/current/plugins-filters-translate.html#plugins-filters-translate-refresh_interval) seconds)

I'm hoping you can help me write a simple CLI app that can be triggered to query the CC for space data and write said `yml` file; which, since it won't need do to any caching etc should hopefully be really simple.

Thoughts?

**Comment by shinji62** [comment]
@mrdavidlaing The mane lookup and space is already on going using boltdb you can check the PR there https://github.com/cloudfoundry-community/firehose-to-syslog/pull/16 is not finished yet, but it s pretty close.

Using boltd is much more flexible than using a plan yam file.

**Comment by shinji62** [comment]
@mrdavidlaing I finish to integrate org, space and apps
So please try out my branch https://github.com/shinji62/firehose-to-syslog/tree/feature/Application_name_lookup

**Comment by shinji62** [comment]
Should be done.

**Comment by mrdavidlaing** [comment]
:+1:
